apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-hook-scripts
  annotations:
    # PreSync 단계에 가장 먼저 생성(-1 wave)
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    # 다음 배포에서 같은 훅을 다시 만들기 직전에만 삭제 (그 외에는 남겨둠)
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  {{- if and .Values.preCheck.enabled .Values.preCheck.scriptName .Values.preCheck.scriptContent }}
  {{ .Values.preCheck.scriptName }}: |
{{ .Values.preCheck.scriptContent | nindent 4 }}
  {{- end }}
  {{- if and .Values.postCheck.enabled .Values.postCheck.scriptName .Values.postCheck.scriptContent }}
  {{ .Values.postCheck.scriptName }}: |
{{ .Values.postCheck.scriptContent | nindent 4 }}
  {{- end }}
