{{- if .Values.preCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  backoffLimit: {{ .Values.preCheck.backoffLimit | default 1 }}
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hook-scripts
          configMap:
            name: {{ include "chart.fullname" . }}-hook-scripts
            defaultMode: 0755
      containers:
        - name: presync
          image: {{ .Values.preCheck.image }}
          volumeMounts:
            - name: hook-scripts
              mountPath: /hooks
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              ls -l /hooks
              /hooks/{{ required "preCheck.scriptName is required" .Values.preCheck.scriptName }}
{{- end }}
