{{- if .Values.preCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    # wave 기본값 0 (CM이 -1이라 먼저 생성됨)
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  backoffLimit: {{ .Values.preCheck.backoffLimit | default 1 }}
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hook-scripts
          configMap:
            name: {{ include "chart.fullname" . }}-hook-scripts
            defaultMode: 0755
      containers:
        - name: presync
          image: {{ .Values.preCheck.image }}
          volumeMounts:
            - name: hook-scripts
              mountPath: /hooks
          env:
            - name: SCRIPT
              value: {{ required "preCheck.scriptName is required" .Values.preCheck.scriptName }}
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euxo pipefail
              echo "[PreSync] scripts in /hooks:"
              ls -l /hooks || true
              # CRLF -> LF 변환 (윈도우 개행 방어)
              for f in /hooks/*; do [ -f "$f" ] && sed -i 's/\r$//' "$f"; done
              chmod +x /hooks/* || true
              echo "[PreSync] running: /hooks/${SCRIPT}"
              /hooks/${SCRIPT}
{{- end }}
