{{- if .Values.postCheck.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  backoffLimit: {{ .Values.postCheck.backoffLimit | default 0 }}
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hook-scripts
          configMap:
            name: {{ include "chart.fullname" . }}-hook-scripts
            defaultMode: 0755
      containers:
        - name: postsync
          image: {{ .Values.postCheck.image }}
          volumeMounts:
            - name: hook-scripts
              mountPath: /hooks
          env:
            - name: SCRIPT
              value: {{ required "postCheck.scriptName is required" .Values.postCheck.scriptName }}
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euxo pipefail
              ls -l /hooks || true
              for f in /hooks/*; do [ -f "$f" ] && sed -i 's/\r$//' "$f"; done
              chmod +x /hooks/* || true
              echo "[PostSync] running: /hooks/${SCRIPT}"
              /hooks/${SCRIPT}
{{- end }}
