apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-presync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: presync
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              echo "[PreSync] 클러스터 DNS 확인 - kubernetes.default.svc"
              nslookup kubernetes.default.svc || { echo "DNS 실패"; exit 1; }
              echo "[PreSync] OK"
